spring:
  application:
    name: myAgent
  ai:
    dashscope:
      api-key: sk-8f66e443e769489eaeadb905c7891f75
      chat:
        options:
          model: qwen-plus
#    vectorstore:
#      pgvector:
#        index-type: HNSW
#        dimensions: 1536
#        distance-type: COSINE_DISTANCE
#        max-document-batch-size: 10000
  datasource:
    url: jdbc:postgresql://rm-cn-m414kfcca0004teo.rwlb.rds.aliyuncs.com:5432/lzz_ai_agent
    username: lzz_user
    password: Lzzl2289
search-api:
  api-key: 2abBfbtrHfdQLfpciw5kFApw

server:
  port: 8080

# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: class list
